version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: bb-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bb_app
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY_DURATION: ${JWT_EXPIRY_DURATION}
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
